### PR TITLE
AUTH: Added authentication service and user information to CERN Bar.

### PR DESCRIPTION
**Pull request by Joscorbe**

### CODE REVIEW

**Comment by icot** [comment]
Please fix the failing test

**Comment by canaltinigne** [comment]
In cern-toolbar.component.spec.ts file,

import { HttpModule } from '@angular/http';
import { AuthenticationService } from './../../services/authentication/authentication.service';

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [HttpModule],
      declarations: [ CernToolbarComponent ],
      providers: [AuthenticationService]
    })
    .compileComponents();
  }));

will fix the test.

**Comment by Joscorbe** [comment]
Fixed, thanks @canaltinigne

**Comment by canaltinigne** [comment]
You're welcome @Joscorbe .

**Pull request merged**
